
{"errorMessage": "[Errno 104] Connection reset by peer", "errorType": "ConnectionResetError", "stackTrace": [["/var/task/app.py", 33, "lambda_handler", "driver = webdriver.Chrome(chrome_options=chrome_options)"], ["/var/task/selenium/webdriver/chrome/webdriver.py", 75, "__init__", "desired_capabilities=desired_capabilities)"], ["/var/task/selenium/webdriver/remote/webdriver.py", 156, "__init__", "self.start_session(capabilities, browser_profile)"], ["/var/task/selenium/webdriver/remote/webdriver.py", 251, "start_session", "response = self.execute(Command.NEW_SESSION, parameters)"], ["/var/task/selenium/webdriver/remote/webdriver.py", 318, "execute", "response = self.command_executor.execute(driver_command, params)"], ["/var/task/selenium/webdriver/remote/remote_connection.py", 472, "execute", "return self._request(command_info[0], url, body=data)"], ["/var/task/selenium/webdriver/remote/remote_connection.py", 496, "_request", "resp = self._conn.getresponse()"], ["/var/lang/lib/python3.6/http/client.py", 1331, "getresponse", "response.begin()"], ["/var/lang/lib/python3.6/http/client.py", 297, "begin", "version, status, reason = self._read_status()"], ["/var/lang/lib/python3.6/http/client.py", 258, "_read_status", "line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")"], ["/var/lang/lib/python3.6/socket.py", 586, "readinto", "return self._sock.recv_into(b)"]]}
